development:
  adapter: mysql
  database: surveytool_development
  username: root
  password:

test: &test
  adapter: mysql
  database: surveytool_test
  username: root
  password:

production:
  adapter: mysql
  database: surveytool_production
  username: root
  password:

cucumber:
  <<: *test